# Generated by Django 4.1.7 on 2023-07-25 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="не более 5000 символов", null=True
            ),
        ),
    ]
